#####
GET http://localhost:8080/users

#####
GET http://localhost:8080/users/2

#####
DELETE http://localhost:8080/users/1

#####
POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "amanda sousa",
    "email": "amanda@gmail.com",
    "password": "123123"
}

#####
PATCH http://localhost:8080/users/2
Content-Type: application/json

{
    "name": "alice sousa almeinda"
}